# Generated by Django 4.0.4 on 2022-04-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_date', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField(default=5)),
                ('buy_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('buyer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Users.user')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Users.user')),
            ],
        ),
    ]
