# Generated by Django 4.0.4 on 2022-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('psswd', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
